services:
  - type: web
    name: smartlibrary-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: PORT
        value: 8081
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        value: https://smartlibrary-app.netlify.app
      - key: APP_ADMIN_EMAIL
        value: divyasreemuppuri@gmail.com
      - key: APP_ADMIN_PASSWORD
        value: admin@123
